#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v spl2c >/dev/null 2>&1; then
  echo "missing toolchain: spl2c" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

spl2c < fizzbuzz.spl > $T/fb.c && cc -o $T/fizzbuzz $T/fb.c -lspl && $T/fizzbuzz
