#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v maxima >/dev/null 2>&1; then
  echo "missing toolchain: maxima" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

maxima --very-quiet < fizzbuzz.mac 2>/dev/null | sed -e 's/[[:space:]]*$//' -e '/^$/d'
