#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v solc >/dev/null 2>&1; then
  echo "missing toolchain: solc" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

solc --bin FizzBuzz.sol >/dev/null && echo 'solidity: compiled (run all() on-chain)'
