#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v kotlinc >/dev/null 2>&1; then
  echo "missing toolchain: kotlinc" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

kotlinc fizzbuzz.kt -include-runtime -d $T/fb.jar 2>/dev/null && java -jar $T/fb.jar
