#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v elm >/dev/null 2>&1; then
  echo "missing toolchain: elm" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

elm make Fizzbuzz.elm --output=$T/elm.html >/dev/null && echo 'elm: build only'
