#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v emojicodec >/dev/null 2>&1; then
  echo "missing toolchain: emojicodec" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

emojicodec fizzbuzz.emojic -o $T/fizzbuzz && $T/fizzbuzz
