#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v futhark >/dev/null 2>&1; then
  echo "missing toolchain: futhark" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

futhark c -o $T/fizzbuzz fizzbuzz.fut && echo 1 | $T/fizzbuzz
