#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v qb64 >/dev/null 2>&1; then
  echo "missing toolchain: qb64" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

qb64 -x fizzbuzz.bas -o $T/fizzbuzz && $T/fizzbuzz
