#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v cc >/dev/null 2>&1; then
  echo "missing toolchain: cc" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

cc -O2 -o $T/bf ../../tools/bf.c && $T/bf fizzbuzz.b
