#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v wat2wasm >/dev/null 2>&1; then
  echo "missing toolchain: wat2wasm" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

wat2wasm fizzbuzz.wat -o $T/fizzbuzz.wasm && wasmtime $T/fizzbuzz.wasm
