#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v bwbasic >/dev/null 2>&1; then
  echo "missing toolchain: bwbasic" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

bwbasic fizzbuzz.bas </dev/null | tr -d '\r' | sed -e '1,4d' | grep -v '^bwBASIC:'
