#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v red >/dev/null 2>&1; then
  echo "missing toolchain: red" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

red --version 2>&1 | grep -qi 'GNU ed' && { echo 'PATH red is restricted ed, not the language' >&2; exit 127; }
red fizzbuzz.red
