#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v mmc >/dev/null 2>&1; then
  echo "missing toolchain: mmc" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

mmc --output-dir $T -o $T/fizzbuzz fizzbuzz.m && $T/fizzbuzz
