#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v chpl >/dev/null 2>&1; then
  echo "missing toolchain: chpl" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

chpl -o $T/fizzbuzz fizzbuzz.chpl && $T/fizzbuzz
