#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v nix-instantiate >/dev/null 2>&1; then
  echo "missing toolchain: nix-instantiate" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

nix-instantiate --eval --strict fizzbuzz.nix | sed -e 's/^"//' -e 's/"$//' -e 's/\\n/\n/g'
