#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
# This implementation is not a stdout program, so the harness cannot diff it.
echo "not runnable here: assemble with ca65/acme, run in a C64 emulator" >&2
exit 127
