#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
# no toolchain probe
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

echo 'asm-6502: assemble with ca65/acme and run in a C64 emulator'
