#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v spim >/dev/null 2>&1; then
  echo "missing toolchain: spim" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

spim -file fizzbuzz.s | sed -e '1,5d'
