#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
# This implementation is not a stdout program, so the harness cannot diff it.
echo "not runnable here: requires SQL Server; returns a result set" >&2
exit 127
