#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v dxc >/dev/null 2>&1; then
  echo "missing toolchain: dxc" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

dxc -T cs_6_0 -E CSMain fizzbuzz.hlsl >/dev/null && echo 'hlsl: compiled (dispatch to see output)'
