#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v gm2 >/dev/null 2>&1; then
  echo "missing toolchain: gm2" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

gm2 -o $T/fizzbuzz fizzbuzz.mod && $T/fizzbuzz
