#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v sbt >/dev/null 2>&1; then
  echo "missing toolchain: sbt" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

sbt -Dsbt.global.base=$T/sbt -batch -error 'runMain FizzBuzzApp' 2>/dev/null | grep -E '^(FizzBuzz|Fizz|Buzz|[0-9]+)$'
