#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v yacas >/dev/null 2>&1; then
  echo "missing toolchain: yacas" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

yacas -pc fizzbuzz.ys | sed -e 's/[[:space:]]*$//'
