#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v gnatmake >/dev/null 2>&1; then
  echo "missing toolchain: gnatmake" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

gnatmake -q -D $T -o $T/fizzbuzz fizzbuzz.adb && $T/fizzbuzz
