#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v vim >/dev/null 2>&1; then
  echo "missing toolchain: vim" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

vim -es -u NONE -c 'source fizzbuzz.vim' -c 'qa!' 2>/dev/null
