#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v riscv64-linux-gnu-as >/dev/null 2>&1; then
  echo "missing toolchain: riscv64-linux-gnu-as" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

riscv64-linux-gnu-as -o $T/fb.o fizzbuzz.s && riscv64-linux-gnu-ld -o $T/fizzbuzz $T/fb.o && qemu-riscv64 $T/fizzbuzz
