#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v fpc >/dev/null 2>&1; then
  echo "missing toolchain: fpc" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

fpc -v0 -FE$T -o$T/fizzbuzz fizzbuzz.pas >/dev/null && $T/fizzbuzz
