#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v haxe >/dev/null 2>&1; then
  echo "missing toolchain: haxe" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

haxe -p . -main Fizzbuzz --interp
