#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v austral >/dev/null 2>&1; then
  echo "missing toolchain: austral" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

austral compile fizzbuzz.aum --entrypoint=Fizzbuzz:main --output=$T/f.c && cc -o $T/fizzbuzz $T/f.c && $T/fizzbuzz
