#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v tex >/dev/null 2>&1; then
  echo "missing toolchain: tex" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

cp fizzbuzz.tex $T/ && (cd $T && tex -interaction=batchmode fizzbuzz.tex >/dev/null 2>&1); cat $T/fizzbuzz.out
