#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v pakcs >/dev/null 2>&1; then
  echo "missing toolchain: pakcs" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

pakcs --quiet :load fizzbuzz :eval main :quit
