#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v javac >/dev/null 2>&1; then
  echo "missing toolchain: javac" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

javac -d $T $(find src -name '*.java') && java -cp $T com.example.enterprise.fizzbuzz.FizzBuzzApplication
