#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v python3 >/dev/null 2>&1; then
  echo "missing toolchain: python3" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

python3 generate.py >/dev/null && cc -O2 -o $T/bf ../../tools/bf.c && python3 ../../tools/ook2bf.py fizzbuzz.ook > $T/fizzbuzz.b && $T/bf $T/fizzbuzz.b
