#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v sass >/dev/null 2>&1; then
  echo "missing toolchain: sass" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

sass --no-source-map fizzbuzz.scss $T/out.css && grep -o 'content: "[^"]*"' $T/out.css | sed -e 's/content: "//' -e 's/"$//'
