#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "missing toolchain: sqlite3" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

sqlite3 -noheader -batch < fizzbuzz.sql
