#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v verilator >/dev/null 2>&1; then
  echo "missing toolchain: verilator" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

verilator --binary --top-module fizzbuzz --Mdir $T fizzbuzz.sv >/dev/null && $T/Vfizzbuzz | grep -v '\$finish'
