#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v as >/dev/null 2>&1; then
  echo "missing toolchain: as" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

as -o $T/fb.o fizzbuzz.s && ld -o $T/fizzbuzz $T/fb.o && $T/fizzbuzz
