#!/usr/bin/env python3
"""Assemble languages/brainfuck/fizzbuzz.b from macros.

Brainfuck has no names, no arithmetic beyond +/-, and no conditionals beyond
"loop while the current cell is non-zero", so writing it directly is mostly
bookkeeping about which tape cell the pointer is sitting on. This module keeps
that bookkeeping in one place and emits the real thing; the committed
fizzbuzz.b is an ordinary Brainfuck program that any interpreter will run.

The algorithm is cycle-based rather than division-based:

  * a two-digit decimal counter (TENS, UNITS) is incremented each pass
  * FIZZC counts 3, 2, 1 and reloads; likewise BUZZC counts 5 .. 1
  * "FizzBuzz" needs no special case -- print "Fizz" then "Buzz"
  * the number is printed only when neither flag fired, so 100 (a Buzz)
    is never printed and two digits are always enough
"""
from pathlib import Path

# Tape layout.
LOOP, TENS, UNITS, FIZZC, BUZZC, FIZZ, BUZZ, T1, T2, T3, ELSE, OUT = range(12)

_code: list[str] = []
_pos = 0


def emit(s: str) -> None:
    _code.append(s)


def to(cell: int) -> None:
    global _pos
    emit(">" * (cell - _pos) if cell > _pos else "<" * (_pos - cell))
    _pos = cell


def add(cell: int, k: int) -> None:
    to(cell)
    emit("+" * k)


def zero(cell: int) -> None:
    to(cell)
    emit("[-]")


def copy(src: int, dst: int, tmp: int) -> None:
    """dst = src, leaving src intact (tmp is clobbered)."""
    zero(dst)
    zero(tmp)
    to(src)
    emit("[")
    add(dst, 1)
    add(tmp, 1)
    to(src)
    emit("-")
    emit("]")
    to(tmp)
    emit("[")
    add(src, 1)
    to(tmp)
    emit("-")
    emit("]")


def if_nonzero(cell: int, body) -> None:
    """Run body if `cell` is non-zero. `cell` is zeroed either way."""
    to(cell)
    emit("[")
    body()
    zero(cell)
    to(cell)
    emit("]")


def if_zero(cell: int, body) -> None:
    """Run body if `cell` is zero. `cell` and ELSE are clobbered."""
    zero(ELSE)
    add(ELSE, 1)
    to(cell)
    emit("[")
    zero(ELSE)
    zero(cell)
    to(cell)
    emit("]")
    to(ELSE)
    emit("[")
    body()
    zero(ELSE)
    to(ELSE)
    emit("]")


def putc(ch: str) -> None:
    zero(OUT)
    add(OUT, ord(ch))
    to(OUT)
    emit(".")


def puts(s: str) -> None:
    for ch in s:
        putc(ch)


def build() -> str:
    # --- initialise -------------------------------------------------------
    add(LOOP, 100)
    add(FIZZC, 3)
    add(BUZZC, 5)

    to(LOOP)
    emit("[")

    # --- increment the decimal counter, with carry ------------------------
    add(UNITS, 1)
    copy(UNITS, T1, T2)
    to(T1)
    emit("-" * 10)
    if_zero(T1, lambda: (zero(UNITS), add(TENS, 1)))

    # --- fizz cycle -------------------------------------------------------
    to(FIZZC)
    emit("-")
    copy(FIZZC, T1, T2)
    if_zero(T1, lambda: (add(FIZZC, 3), add(FIZZ, 1)))

    # --- buzz cycle -------------------------------------------------------
    to(BUZZC)
    emit("-")
    copy(BUZZC, T1, T2)
    if_zero(T1, lambda: (add(BUZZC, 5), add(BUZZ, 1)))

    # --- output -----------------------------------------------------------
    copy(FIZZ, T1, T2)
    if_nonzero(T1, lambda: puts("Fizz"))

    copy(BUZZ, T1, T2)
    if_nonzero(T1, lambda: puts("Buzz"))

    # T3 = FIZZ + BUZZ; if it is zero, neither fired, so print the number.
    zero(T3)
    copy(FIZZ, T1, T2)
    to(T1)
    emit("[")
    add(T3, 1)
    to(T1)
    emit("-")
    emit("]")
    copy(BUZZ, T1, T2)
    to(T1)
    emit("[")
    add(T3, 1)
    to(T1)
    emit("-")
    emit("]")

    def print_number() -> None:
        # leading zero suppression: only print TENS when it is non-zero
        copy(TENS, T1, T2)
        def tens_digit() -> None:
            copy(TENS, OUT, T2)
            add(OUT, 48)
            to(OUT)
            emit(".")
        if_nonzero(T1, tens_digit)
        copy(UNITS, OUT, T2)
        add(OUT, 48)
        to(OUT)
        emit(".")

    if_zero(T3, print_number)

    putc("\n")

    zero(FIZZ)
    zero(BUZZ)

    to(LOOP)
    emit("-")
    emit("]")

    return "".join(_code)


def main() -> None:
    code = build()
    out = Path(__file__).resolve().parent.parent / "languages" / "brainfuck" / "fizzbuzz.b"
    out.parent.mkdir(parents=True, exist_ok=True)
    # Brainfuck has no comment syntax: everything outside the eight command
    # characters is ignored, which means a prose header must avoid them
    # entirely. A stray "." in "gen_brainfuck.py" is an output instruction.
    header = (
        "FizzBuzz in Brainfuck\n"
        "Generated by tools/gen_brainfuck (see that file for the tape layout\n"
        "and the cycle based algorithm)\n"
        "Tape cells: LOOP TENS UNITS FIZZC BUZZC FIZZ BUZZ T1 T2 T3 ELSE OUT\n\n"
    )
    stray = set(header) & set("><+-.,[]")
    if stray:
        raise SystemExit(f"header contains Brainfuck commands: {sorted(stray)}")
    wrapped = "\n".join(code[i : i + 72] for i in range(0, len(code), 72))
    out.write_text(header + wrapped + "\n")
    print(f"wrote {out} ({len(code)} instructions)")


if __name__ == "__main__":
    main()
