#!/usr/bin/env python3
"""Write languages/<slug>/run.sh for every entry in the manifest."""
import os
import stat
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from manifest import LANGUAGES  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
LANG_DIR = ROOT / "languages"

TEMPLATE = """#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
{probe}
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

{body}
"""

PROBE = """if ! command -v {tool} >/dev/null 2>&1; then
  echo "missing toolchain: {tool}" >&2
  exit 127
fi"""


def main() -> int:
    missing = []
    for slug, (tool, body) in sorted(LANGUAGES.items()):
        d = LANG_DIR / slug
        if not d.is_dir():
            missing.append(slug)
            continue
        probe = PROBE.format(tool=tool) if tool else "# no toolchain probe"
        path = d / "run.sh"
        path.write_text(TEMPLATE.format(probe=probe, body=body))
        path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    extra = sorted(
        p.name for p in LANG_DIR.iterdir() if p.is_dir() and p.name not in LANGUAGES
    )

    print(f"generated {len(LANGUAGES) - len(missing)} runners")
    if missing:
        print(f"manifest entries with no directory: {', '.join(missing)}")
    if extra:
        print(f"directories with no manifest entry: {', '.join(extra)}")
    return 1 if (missing or extra) else 0


if __name__ == "__main__":
    raise SystemExit(main())
