#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
# no toolchain probe
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

echo 'asm-z80: assemble with z80asm and run under a CP/M emulator'
