#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v gs >/dev/null 2>&1; then
  echo "missing toolchain: gs" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

gs -q -dBATCH -dNOPAUSE -dNODISPLAY fizzbuzz.ps
