#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v factor >/dev/null 2>&1; then
  echo "missing toolchain: factor" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

factor --version 2>&1 | grep -qi coreutils && { echo 'PATH factor is coreutils, not the language' >&2; exit 127; }
factor fizzbuzz.factor
