#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
# This implementation is not a stdout program, so the harness cannot diff it.
echo "not runnable here: renders to a framebuffer, not stdout" >&2
exit 127
