/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-8-14: 12h:35m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_g0int_mod_int)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_g0int_lte_int)
ATSdyncst_mac(atspre_g0int_add_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatic()
atsvoid_t0ype
fizzbuzz_0(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_0_void() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
loop_9(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lte_g0int_int__10(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lte_g0int_int__10__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 43(line=3, offs=5) -- 217(line=7, offs=20)
*/
/*
local: 
global: fizzbuzz_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
fizzbuzz_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp7) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp12) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp17) ;
// ATStmpdec_void(tmp18) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 43(line=3, offs=5) -- 217(line=7, offs=20)
*/
ATSINSflab(__patsflab_fizzbuzz_0):
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 74(line=4, offs=6) -- 80(line=4, offs=12)
*/
ATSINSmove(tmp6, atspre_g0int_mod_int(arg0, ATSPMVi0nt(15))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 74(line=4, offs=6) -- 84(line=4, offs=16)
*/
ATSINSmove(tmp1, ATSLIB_056_prelude__eq_g0int_int__1__1(tmp6, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 71(line=4, offs=3) -- 217(line=7, offs=20)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 90(line=4, offs=22) -- 111(line=4, offs=43)
*/
ATSINSmove_void(tmp7, atspre_print_string(ATSPMVstring("FizzBuzz"))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 90(line=4, offs=22) -- 111(line=4, offs=43)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 122(line=5, offs=11) -- 127(line=5, offs=16)
*/
ATSINSmove(tmp11, atspre_g0int_mod_int(arg0, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 122(line=5, offs=11) -- 131(line=5, offs=20)
*/
ATSINSmove(tmp8, ATSLIB_056_prelude__eq_g0int_int__1__2(tmp11, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 119(line=5, offs=8) -- 217(line=7, offs=20)
*/
ATSif(
tmp8
) ATSthen() {
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 137(line=5, offs=26) -- 154(line=5, offs=43)
*/
ATSINSmove_void(tmp12, atspre_print_string(ATSPMVstring("Fizz"))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 137(line=5, offs=26) -- 154(line=5, offs=43)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 165(line=6, offs=11) -- 170(line=6, offs=16)
*/
ATSINSmove(tmp16, atspre_g0int_mod_int(arg0, ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 165(line=6, offs=11) -- 174(line=6, offs=20)
*/
ATSINSmove(tmp13, ATSLIB_056_prelude__eq_g0int_int__1__3(tmp16, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 162(line=6, offs=8) -- 217(line=7, offs=20)
*/
ATSif(
tmp13
) ATSthen() {
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 180(line=6, offs=26) -- 197(line=6, offs=43)
*/
ATSINSmove_void(tmp17, atspre_print_string(ATSPMVstring("Buzz"))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 180(line=6, offs=26) -- 197(line=6, offs=43)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 205(line=7, offs=8) -- 217(line=7, offs=20)
*/
ATSINSmove_void(tmp18, atspre_print_int(arg0)) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 205(line=7, offs=8) -- 217(line=7, offs=20)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [fizzbuzz_0] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp3, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4634))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret2, PMVtmpltcst(g0int_eq<S2Evar(tk(4634))>)(arg0, tmp3)) ;

ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp3__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret2__1, atspre_g0int_eq_int(arg0, tmp3__1)) ;

ATSfunbody_end()
ATSreturn(tmpret2__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__1] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp3__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret2__2, atspre_g0int_eq_int(arg0, tmp3__2)) ;

ATSfunbody_end()
ATSreturn(tmpret2__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__2] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$1$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp3__3, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret2__3, atspre_g0int_eq_int(arg0, tmp3__3)) ;

ATSfunbody_end()
ATSreturn(tmpret2__3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__3] */

/*
/home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 235(line=9, offs=17) -- 339(line=14, offs=4)
*/
/*
local: fizzbuzz_0$0(level=0)
global: fizzbuzz_0$0(level=0), mainats_0_void$8$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_0_void()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret19) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 229(line=9, offs=11) -- 339(line=14, offs=4)
*/
ATSINSflab(__patsflab_main_0_void):
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 240(line=9, offs=22) -- 339(line=14, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 327(line=13, offs=3) -- 335(line=13, offs=11)
*/
ATSINSmove_void(tmpret19, loop_9(ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 240(line=9, offs=22) -- 339(line=14, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret19) ;
} /* end of [mainats_0_void] */

/*
/home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 250(line=10, offs=7) -- 321(line=11, offs=50)
*/
/*
local: fizzbuzz_0$0(level=0), loop_9$0(level=1)
global: fizzbuzz_0$0(level=0), loop_9$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_9(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmpret20) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp26) ;
ATStmpdec(tmp27, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 250(line=10, offs=7) -- 321(line=11, offs=50)
*/
ATSINSflab(__patsflab_loop_9):
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 279(line=11, offs=8) -- 287(line=11, offs=16)
*/
ATSINSmove(tmp21, ATSLIB_056_prelude__lte_g0int_int__10__1(arg0, ATSPMVi0nt(100))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 276(line=11, offs=5) -- 321(line=11, offs=50)
*/
ATSif(
tmp21
) ATSthen() {
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 294(line=11, offs=23) -- 305(line=11, offs=34)
*/
ATSINSmove_void(tmp26, fizzbuzz_0(arg0)) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 314(line=11, offs=43) -- 319(line=11, offs=48)
*/
ATSINSmove(tmp27, atspre_g0int_add_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 308(line=11, offs=37) -- 320(line=11, offs=49)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp27) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSfgoto(__patsflab_loop_9) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /home/user/fizz-buzz-every-language/languages/ats/fizzbuzz.dats: 321(line=11, offs=50) -- 321(line=11, offs=50)
*/
ATSINSmove_void(tmpret20, ATSPMVempty()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret20) ;
} /* end of [loop_9] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12019(line=621, offs=3) -- 12059(line=621, offs=43)
*/
/*
local: 
global: lte_g0int_int$10$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4631)
tmparg = S2Evar(tk(4631))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lte_g0int_int__10(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12003(line=620, offs=1) -- 12059(line=621, offs=43)
*/
ATSINSflab(__patsflab_lte_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12046(line=621, offs=30) -- 12057(line=621, offs=41)
*/
ATSINSmove(tmp23, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4631))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12028(line=621, offs=12) -- 12059(line=621, offs=43)
*/
ATSINSmove(tmpret22, PMVtmpltcst(g0int_lte<S2Evar(tk(4631))>)(arg0, tmp23)) ;

ATSfunbody_end()
ATSreturn(tmpret22) ;
} /* end of [ATSLIB_056_prelude__lte_g0int_int__10] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12019(line=621, offs=3) -- 12059(line=621, offs=43)
*/
/*
local: 
global: lte_g0int_int$10$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4631)
tmparg = S2Evar(tk(4631))
tmpsub = Some(tk(4631) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lte_g0int_int__10__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp23__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12003(line=620, offs=1) -- 12059(line=621, offs=43)
*/
ATSINSflab(__patsflab_lte_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12046(line=621, offs=30) -- 12057(line=621, offs=41)
*/
ATSINSmove(tmp23__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12028(line=621, offs=12) -- 12059(line=621, offs=43)
*/
ATSINSmove(tmpret22__1, atspre_g0int_lte_int(arg0, tmp23__1)) ;

ATSfunbody_end()
ATSreturn(tmpret22__1) ;
} /* end of [ATSLIB_056_prelude__lte_g0int_int__10__1] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_user_057_fizz_055_buzz_055_every_055_language_057_languages_057_ats_057_fizzbuzz_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_user_057_fizz_055_buzz_055_every_055_language_057_languages_057_ats_057_fizzbuzz_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_user_057_fizz_055_buzz_055_every_055_language_057_languages_057_ats_057_fizzbuzz_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_user_057_fizz_055_buzz_055_every_055_language_057_languages_057_ats_057_fizzbuzz_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_user_057_fizz_055_buzz_055_every_055_language_057_languages_057_ats_057_fizzbuzz_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_user_057_fizz_055_buzz_055_every_055_language_057_languages_057_ats_057_fizzbuzz_056_dats__dynload() ;
ATSmainats_0_void(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
