#!/usr/bin/env bash
# Generated by tools/generate_runners.py -- edit tools/manifest.py instead.
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v patscc >/dev/null 2>&1; then
  echo "missing toolchain: patscc" >&2
  exit 127
fi
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

patscc -o $T/fizzbuzz fizzbuzz.dats && $T/fizzbuzz
